# Server Configuration
server:
    port: 8081
    servlet:
        context-path: /api

# Spring Configuration
spring:
    # PostgreSQL Configuration
    datasource:
        url: jdbc:postgresql://localhost:5432/docuflow
        username: postgres
        password: Networking250
        driver-class-name: org.postgresql.Driver

    # JPA Configuration
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    # MongoDB Configuration
    data:
        mongodb:
            uri: mongodb://localhost:27017/docuflow
            auto-index-creation: true

# Pulsar Configuration
pulsar:
    service-url: pulsar://localhost:6650
    admin-url: http://localhost:8080
    tenant: public
    namespace: default

# Logging Configuration
logging:
    level:
        root: INFO
        "[com.example.docuflow_backend]": DEBUG
        "[org.springframework.data]": INFO
        "[org.springframework.web]": INFO
